config/routes.rb
Puns::Application.routes.draw do
  resources :puns

  resources :users

end

app/models/pun.rb
class Pun < ActiveRecord::Base
  attr_accessible :content, :user_id
end

class Pun < ActiveRecord::Base
  belongs_to :user
  
  validates :content,  :length => { :maximum => 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
end

class User < ActiveRecord::Base
  has_many :puns
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/puns_controller.rb
class PunsController < ApplicationController
  # GET /puns
  # GET /puns.json
  def index
    @puns = Pun.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @puns }
    end
  end

  # GET /puns/1
  # GET /puns/1.json
  def show
    @pun = Pun.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pun }
    end
  end

  # GET /puns/new
  # GET /puns/new.json
  def new
    @pun = Pun.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pun }
    end
  end

  # GET /puns/1/edit
  def edit
    @pun = Pun.find(params[:id])
  end

  # POST /puns
  # POST /puns.json
  def create
    @pun = Pun.new(params[:pun])

    respond_to do |format|
      if @pun.save
        format.html { redirect_to @pun, notice: 'Pun was successfully created.' }
        format.json { render json: @pun, status: :created, location: @pun }
      else
        format.html { render action: "new" }
        format.json { render json: @pun.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /puns/1
  # PUT /puns/1.json
  def update
    @pun = Pun.find(params[:id])

    respond_to do |format|
      if @pun.update_attributes(params[:pun])
        format.html { redirect_to @pun, notice: 'Pun was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pun.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puns/1
  # DELETE /puns/1.json
  def destroy
    @pun = Pun.find(params[:id])
    @pun.destroy

    respond_to do |format|
      format.html { redirect_to puns_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/puns_helper.rb
module PunsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Puns</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/puns/_form.html.erb
<%= form_for(@pun) do |f| %>
  <% if @pun.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pun.errors.count, "error") %> prohibited this pun from being saved:</h2>

      <ul>
      <% @pun.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/puns/edit.html.erb
<h1>Editing pun</h1>

<%= render 'form' %>

<%= link_to 'Show', @pun %> |
<%= link_to 'Back', puns_path %>

app/views/puns/index.html.erb
<h1>puns</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<!-- <% @puns.each do |pun| %>
  <tr>
    <td><%= pun.content %></td>
    <td><%= pun.user_id %></td>
    <td><%= link_to 'Show', pun %></td>
    <td><%= link_to 'Edit', edit_pun_path(pun) %></td>
    <td><%= link_to 'Destroy', pun, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table> -->

<% @puns.each do |pun| %>
  <ul>
    <li><%= pun.content %>
    <span class="user"><%= pun.user_id %></span> --
    <span class="crud>"<%= link_to 'Show', pun %>
    <%= link_to 'Edit', edit_pun_path(pun) %>
    <%= link_to 'Destroy', pun, confirm: 'Are you sure?', method: :delete %></span>
  </ul>
<% end %>



<br />

<%= link_to 'New Pun', new_pun_path %>

app/views/puns/new.html.erb
<h1>New pun</h1>

<%= render 'form' %>

<%= link_to 'Back', puns_path %>

app/views/puns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @pun.content %>
</p>

<p>
  <b>User:</b>
  <%= @pun.user_id %>
</p>


<%= link_to 'Edit', edit_pun_path(@pun) %> |
<%= link_to 'Back', puns_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<!-- <table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table> -->
<ul>
	<% @users.each do |user| %>
	  <li>
	    <%= user.name %>  
		E:<%= user.email %> --
		<%= link_to 'Show', user %>
	    <%= link_to 'Edit', edit_user_path(user) %>
	    <%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %>
	  </li>
	<% end %>

</ul>
<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>